"""
Real MSU Gweru data - sourced from msu.ac.zw, GDSC community, news articles.
All organizations are verified real entities at Midlands State University, Gweru, Zimbabwe.
"""

# ── CLUBS (verified from msu.ac.zw Student Development Office) ──────────────
CLUBS = [
    {
        'name': 'Enactus MSU',
        'category': 'business',
        'description': 'Entrepreneurial action organization. Multiple-time Zimbabwe National Champions, represented Zimbabwe at Enactus World Cup in London and Silicon Valley. Known for community projects including "Gold in Garbage" waste management in Senga, "Tsapo Bag" thermostatic bags from recycled materials, and inmate empowerment programs in Shurugwi.',
        'email': 'enactus@msu.ac.zw',
        'website': 'https://enactus.org',
        'meeting_location': 'Commerce Faculty Block',
        'meeting_schedule': 'Wednesdays 16:00-18:00',
        'categories': 'business,entrepreneurship,community service,social enterprise',
    },
    {
        'name': 'GDG on Campus MSU',
        'category': 'technology',
        'description': 'Google Developer Group on Campus (formerly GDSC). Organizes tech events including TechConnect, GDGOC Connect, Girls in ICT Day, and Build With AI sessions. Focus on AI, Firebase, web development and community building.',
        'email': 'gdg.msu@msu.ac.zw',
        'website': 'https://gdsc.community.dev/midlands-state-university/',
        'meeting_location': 'West Lecture Theatre',
        'meeting_schedule': 'Saturdays 10:00-13:00',
        'categories': 'technology,coding,AI,Google,developer',
    },
    {
        'name': 'MSU Great Debaters',
        'category': 'academic',
        'description': 'Award-winning debating society competing at WUDC (World Universities Debating Championship) and PAUDC (Pan African Universities Debating Championship). Consistently achieves honors in competitive debating and public speaking.',
        'email': 'debates@msu.ac.zw',
        'website': '',
        'meeting_location': 'Main Lecture Theatre',
        'meeting_schedule': 'Tuesdays and Thursdays 17:00-19:00',
        'categories': 'debating,public speaking,critical thinking,academic',
    },
    {
        'name': 'Rotaract Club of MSU',
        'category': 'service',
        'description': 'Community service club affiliated with Rotary International. Focus on charitable outreach including donating stationery to Senga Primary School and educational supply drives for underprivileged students in Gweru.',
        'email': 'rotaract@msu.ac.zw',
        'website': '',
        'meeting_location': 'Student Centre',
        'meeting_schedule': 'Thursdays 17:00-18:30',
        'categories': 'community service,charity,leadership,volunteering',
    },
    {
        'name': 'Leo Club MSU',
        'category': 'service',
        'description': 'Lions Clubs International youth program. Members serve on Leo Club Program Advisory Panel representing Africa globally. Recipients of "World Leo of the Year" award. Active in District 412 (Zimbabwe & Botswana) leadership.',
        'email': 'leoclub@msu.ac.zw',
        'website': '',
        'meeting_location': 'Student Centre',
        'meeting_schedule': 'Wednesdays 17:00-18:30',
        'categories': 'community service,international,leadership,volunteering',
    },
    {
        'name': 'Business Management Association',
        'category': 'business',
        'description': 'Professional association for Commerce faculty students. Organizes business plan competitions, entrepreneurship workshops, networking events with industry professionals, and career guidance sessions.',
        'email': 'bma@msu.ac.zw',
        'website': '',
        'meeting_location': 'Commerce Faculty Block',
        'meeting_schedule': 'Fridays 14:00-16:00',
        'categories': 'business,management,entrepreneurship,professional',
    },
    {
        'name': 'Young Ambassadors Forum',
        'category': 'academic',
        'description': 'Student association promoting dialogue, diplomacy, and international relations awareness. Hosts forums on current affairs, Model UN simulations, and diplomatic engagement activities.',
        'email': 'yaf@msu.ac.zw',
        'website': '',
        'meeting_location': 'Arts Faculty Block',
        'meeting_schedule': 'Mondays 16:00-17:30',
        'categories': 'diplomacy,dialogue,international relations,leadership',
    },
    {
        'name': 'Padare',
        'category': 'service',
        'description': 'Gender advocacy and discourse organization. Promotes dialogue on gender-based violence awareness, conducts research, and facilitates discussions on gender equality and social justice at MSU.',
        'email': 'padare@msu.ac.zw',
        'website': '',
        'meeting_location': 'Social Sciences Block',
        'meeting_schedule': 'Tuesdays 16:00-17:30',
        'categories': 'gender,advocacy,social justice,community',
    },
    {
        'name': 'Team Destiny',
        'category': 'service',
        'description': 'Student-driven charity initiative focused on psycho-social well-being of the university community. Conducts outreach programs, mentorship, and community development projects aligned with MSU vision of producing enterprising students.',
        'email': 'teamdestiny@msu.ac.zw',
        'website': '',
        'meeting_location': 'Student Centre',
        'meeting_schedule': 'Saturdays 09:00-11:00',
        'categories': 'charity,mentorship,well-being,community service',
    },
    {
        'name': 'MSU Association of Students in Mining',
        'category': 'academic',
        'description': 'Professional organization for mining engineering students (MSU ASIM). Cultivates passion for mining, provides networking with industry, organizes workshops, field trips, and hands-on industrial experience.',
        'email': 'asim@msu.ac.zw',
        'website': '',
        'meeting_location': 'Engineering Block',
        'meeting_schedule': 'Fridays 15:00-17:00',
        'categories': 'mining,engineering,professional,industry',
    },
]

# ── CHURCHES (verified from MSU Chaplaincy / Student Affairs) ───────────────
CHURCHES = [
    {
        'name': 'Christian Union',
        'denomination': 'other',
        'description': 'Interdenominational campus fellowship. One of the largest student Christian organizations at MSU. Regular Bible studies, worship services, and evangelism outreach.',
        'email': 'christianunion@msu.ac.zw',
        'pastor_name': '',
        'service_times': {'Tuesday': '17:30-20:00', 'Thursday': '17:30-20:00', 'Sunday': '09:00-12:00'},
        'categories': 'christian,interdenominational,worship,bible study',
    },
    {
        'name': 'AFMOC (AFM on Campus)',
        'denomination': 'pentecostal',
        'description': 'Apostolic Faith Mission on Campus. Pentecostal fellowship for AFM students with vibrant worship, prayer meetings, and spiritual growth programs.',
        'email': 'afmoc@msu.ac.zw',
        'pastor_name': '',
        'service_times': {'Thursday': '17:00-19:00', 'Sunday': '09:00-12:00'},
        'categories': 'pentecostal,apostolic,worship,prayer',
    },
    {
        'name': 'ZAOGA Forward in Faith',
        'denomination': 'pentecostal',
        'description': 'Zimbabwe Assemblies of God Africa campus chapter. Prayer meetings, worship services, and youth ministry activities on campus.',
        'email': 'zaoga@msu.ac.zw',
        'pastor_name': '',
        'service_times': {'Thursday': '18:00-20:00', 'Sunday': '09:00-12:00'},
        'categories': 'pentecostal,prayer,worship,youth',
    },
    {
        'name': 'SDA Student Fellowship',
        'denomination': 'other',
        'description': 'Seventh-day Adventist campus fellowship. Sabbath worship services, mid-week prayer meetings, and health ministry outreach programs.',
        'email': 'sda@msu.ac.zw',
        'pastor_name': '',
        'service_times': {'Wednesday': '17:00-19:00', 'Friday': '17:00-19:00', 'Saturday': '09:00-16:00'},
        'categories': 'adventist,sabbath,health,worship',
    },
    {
        'name': 'Christ Embassy MSU',
        'denomination': 'pentecostal',
        'description': 'Christ Embassy campus fellowship (BLW). Sunday worship services, mid-week services, and campus evangelism under the Loveworld ministry.',
        'email': 'christembassy@msu.ac.zw',
        'pastor_name': '',
        'service_times': {'Wednesday': '17:00-19:00', 'Sunday': '11:00-13:00'},
        'categories': 'pentecostal,loveworld,worship,evangelism',
    },
    {
        'name': 'Catholic Society',
        'denomination': 'catholic',
        'description': 'Catholic students fellowship associated with St. Mary\'s Parish and the Diocese of Gweru. Regular mass, rosary groups, and Catholic social teaching study groups.',
        'email': 'catholic@msu.ac.zw',
        'pastor_name': '',
        'service_times': {'Sunday': '08:00-10:00', 'Wednesday': '17:30-18:30'},
        'categories': 'catholic,mass,rosary,faith',
    },
    {
        'name': 'PHD Ministries',
        'denomination': 'pentecostal',
        'description': 'Prophetic Healing and Deliverance Ministries campus chapter. Worship services and prayer meetings for PHD members on campus.',
        'email': 'phd@msu.ac.zw',
        'pastor_name': '',
        'service_times': {'Thursday': '17:00-19:00', 'Sunday': '09:00-12:00'},
        'categories': 'pentecostal,prophetic,worship,healing',
    },
    {
        'name': 'UFIC Campus Fellowship',
        'denomination': 'pentecostal',
        'description': 'United Family International Church campus chapter. Fellowship, worship, and prayer gatherings for UFIC students at MSU.',
        'email': 'ufic@msu.ac.zw',
        'pastor_name': '',
        'service_times': {'Thursday': '17:00-19:00', 'Sunday': '10:00-12:00'},
        'categories': 'pentecostal,fellowship,worship,prayer',
    },
]

# ── SPORTS TEAMS (verified from MSU Dept of Sports & Recreation, ZUSA) ─────
SPORTS_TEAMS = [
    {
        'name': 'MSU Sharks',
        'sport_type': 'football',
        'division': 'mens',
        'description': 'Men\'s football team competing in the ZIFA Central Region Soccer League (Division One). One of MSU\'s most prominent sports teams with strong support base.',
        'email': 'sharks@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Mon/Wed/Fri 15:00-17:00',
        'categories': 'football,soccer,ZIFA,competitive',
    },
    {
        'name': 'MSU Jaguars',
        'sport_type': 'football',
        'division': 'womens',
        'description': 'Women\'s football team competing in the Zimbabwe Women\'s Soccer League (top-flight). Representing MSU at the highest level of women\'s football in Zimbabwe.',
        'email': 'jaguars@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Mon/Wed/Fri 15:00-17:00',
        'categories': 'football,soccer,women,competitive',
    },
    {
        'name': 'MSU Basketball',
        'sport_type': 'basketball',
        'division': 'mixed',
        'description': 'University basketball program competing in ZUSA inter-university tournaments. Regular participation in cluster games with strong medal record.',
        'email': 'basketball@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Tue/Thu 16:00-18:00',
        'categories': 'basketball,ZUSA,competitive',
    },
    {
        'name': 'MSU Volleyball',
        'sport_type': 'volleyball',
        'division': 'mixed',
        'description': 'Volleyball teams (men\'s and women\'s) competing in ZUSA tournaments. Consistent performers at inter-university level across Zimbabwe.',
        'email': 'volleyball@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Mon/Wed 16:00-18:00',
        'categories': 'volleyball,ZUSA,competitive',
    },
    {
        'name': 'MSU Netball',
        'sport_type': 'other',
        'division': 'womens',
        'description': 'Women\'s netball team representing MSU at ZUSA games. Strong competitive record with medal finishes at national university tournaments.',
        'email': 'netball@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Tue/Thu 15:00-17:00',
        'categories': 'netball,women,ZUSA,competitive',
    },
    {
        'name': 'MSU Athletics',
        'sport_type': 'athletics',
        'division': 'mixed',
        'description': 'Track and field program. MSU consistently tops ZUSA medal tables in athletics. Trains sprinters, middle-distance, long-distance runners, and field event athletes.',
        'email': 'athletics@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Mon-Fri 05:30-07:00',
        'categories': 'athletics,track,field,ZUSA,competitive',
    },
    {
        'name': 'MSU Tennis',
        'sport_type': 'tennis',
        'division': 'mixed',
        'description': 'Tennis program for competitive and recreational players. Participates in ZUSA tournaments and inter-university friendly matches.',
        'email': 'tennis@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Tue/Thu/Sat 07:00-09:00',
        'categories': 'tennis,racquet,ZUSA',
    },
    {
        'name': 'MSU Hockey',
        'sport_type': 'other',
        'division': 'mixed',
        'description': 'Field hockey teams competing in ZUSA inter-university games. Both men\'s and women\'s squads participate in cluster tournaments.',
        'email': 'hockey@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Wed/Fri 15:00-17:00',
        'categories': 'hockey,field hockey,ZUSA',
    },
    {
        'name': 'MSU Chess Club',
        'sport_type': 'other',
        'division': 'mixed',
        'description': 'Competitive chess team participating in ZUSA chess tournaments. Open to all skill levels with regular training sessions and internal tournaments.',
        'email': 'chess@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Saturdays 14:00-17:00',
        'categories': 'chess,mind sport,strategy',
    },
    {
        'name': 'MSU Cricket',
        'sport_type': 'other',
        'division': 'mens',
        'description': 'Cricket team participating in inter-university tournaments. Regular training and competitive fixtures through ZUSA cricket program.',
        'email': 'cricket@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Sat/Sun 08:00-12:00',
        'categories': 'cricket,bat,ZUSA',
    },
    {
        'name': 'MSU Karate',
        'sport_type': 'other',
        'division': 'mixed',
        'description': 'Martial arts program covering karate and taekwondo. Competes in ZUSA martial arts events. Training for beginners and advanced students.',
        'email': 'karate@msu.ac.zw',
        'coach': '',
        'practice_schedule': 'Mon/Wed/Fri 17:00-19:00',
        'categories': 'karate,taekwondo,martial arts',
    },
]

# ── ACTIVITIES (based on real MSU events from news/social media) ────────────
ACTIVITIES = [
    {
        'name': 'GDGOC Connect 2025: Code, Community & Chill',
        'activity_type': 'social',
        'description': 'GDG on Campus MSU kickoff event. Networking and social gathering introducing new and returning members. Focus on exploring AI-powered solutions throughout 2025.',
        'location': 'West Lecture Theatre',
    },
    {
        'name': 'International Girls in ICT Day',
        'activity_type': 'seminar',
        'description': 'Promoting gender diversity in tech. Features insights from women in the industry on bridging the digital gender gap and essential skills for women entering tech.',
        'location': 'Main Lecture Theatre',
    },
    {
        'name': 'Build With AI: Vibe Coding',
        'activity_type': 'workshop',
        'description': 'Exploring AI-assisted coding with live demos of Gemini, Firebase GenAI Studio, and Cursor. Collaboration with GDG on Campus at NUST.',
        'location': 'Online (Virtual)',
    },
    {
        'name': 'Enactus National Competition',
        'activity_type': 'competition',
        'description': 'Annual Enactus Zimbabwe National Competition. MSU Enactus team presents community impact projects for chance to represent Zimbabwe at Enactus World Cup.',
        'location': 'Harare International Conference Centre',
    },
    {
        'name': 'ZUSA Inter-University Games',
        'activity_type': 'competition',
        'description': 'Zimbabwe Universities Sports Association annual tournament. MSU teams compete across multiple sports codes against other Zimbabwean universities.',
        'location': 'MSU Sports Complex',
    },
    {
        'name': 'MSU Career Fair',
        'activity_type': 'conference',
        'description': 'Annual career fair connecting MSU students with potential employers. Features company booths, CV workshops, and networking sessions with industry professionals.',
        'location': 'Great Hall',
    },
    {
        'name': 'FIFA/CIES Sports Management Programme Launch',
        'activity_type': 'seminar',
        'description': 'MSU-ZIFA partnership launching the FIFA/CIES International Programme in Sports Management at MSU, the first of its kind in Zimbabwe.',
        'location': 'Great Hall',
    },
    {
        'name': 'TechConnect: Reflect, Inspire, Elevate',
        'activity_type': 'conference',
        'description': 'Virtual end-of-year event in collaboration with GDG on Campus groups from Federal University Dutse and University of Benin (Nigeria). Celebrates achievements and plans for 2025.',
        'location': 'Online (Virtual)',
    },
]

# ── ZIMBABWEAN NAMES (authentic Shona/Ndebele names) ───────────────────────
FIRST_NAMES_MALE = [
    'Tanaka', 'Tinashe', 'Tendai', 'Takudzwa', 'Tafadzwa', 'Farai',
    'Simba', 'Tawanda', 'Munyaradzi', 'Tichaona', 'Panashe', 'Tatenda',
    'Kudakwashe', 'Tapiwa', 'Tinotenda', 'Tongai', 'Taurai', 'Nyasha',
    'Munashe', 'Anesu', 'Tadiwanashe', 'Kudzai', 'Terrence', 'Brian',
]

FIRST_NAMES_FEMALE = [
    'Rumbi', 'Chipo', 'Rudo', 'Tariro', 'Rutendo', 'Vimbai',
    'Kundai', 'Varaidzo', 'Nyasha', 'Tsitsi', 'Yeukai', 'Makanaka',
    'Rufaro', 'Tendai', 'Blessing', 'Memory', 'Mercy', 'Shumirai',
    'Shamiso', 'Chenai', 'Ruvarashe', 'Nokutenda', 'Mitchelle', 'Sharon',
]

LAST_NAMES = [
    'Moyo', 'Ncube', 'Sibanda', 'Dube', 'Ndlovu', 'Mpofu',
    'Khumalo', 'Nkomo', 'Nyathi', 'Mthembu', 'Mlilo', 'Tshuma',
    'Banda', 'Phiri', 'Mwale', 'Tembo', 'Zimba', 'Mbewe',
    'Chimedza', 'Chikwanha', 'Mutasa', 'Gumbo', 'Mupfumira', 'Chirwa',
    'Chivasa', 'Madziva', 'Maposa', 'Musoni', 'Zvobgo', 'Chikumba',
]

# MSU Faculties (verified from msu.ac.zw)
FACULTIES = {
    'agriculture': ['Agricultural Economics', 'Crop Science', 'Animal Science'],
    'arts': ['English', 'History', 'Development Studies', 'Media Studies'],
    'commerce': ['Accounting', 'Banking and Finance', 'Business Management', 'Marketing', 'Insurance and Risk Management'],
    'education': ['Educational Foundations', 'Curriculum Studies', 'Adult Education'],
    'law': ['Public Law', 'Private Law', 'Procedural Law'],
    'science': ['Computer Science', 'Mathematics', 'Physics', 'Chemistry', 'Biological Sciences', 'Geography'],
    'social_sciences': ['Psychology', 'Sociology', 'Economics', 'Politics and Public Management', 'Local Governance'],
}

# Real post content templates reflecting MSU campus life
POST_TEMPLATES = {
    'club': [
        'Meeting this {day} at {location}. All members welcome! #MSU #StudentLife',
        'Congratulations to our team for an amazing performance at the competition! #MSUPride',
        'Applications now open for new members. Join us and be part of something great! #JoinUs',
        'Workshop coming up this weekend. Register now - limited spots available!',
        'Community outreach day was a success! Thank you to all volunteers. #CommunityService',
    ],
    'church': [
        'Join us for worship this {day}. All are welcome! #CampusFaith',
        'Prayer meeting tonight. Let us come together in fellowship. #Prayer',
        'Bible study group starts this week. New members welcome!',
        'Special thanksgiving service this Sunday. Don\'t miss it!',
    ],
    'sports': [
        'Match day! Come support your team at the sports complex! #GoMSU',
        'Training resumes this week. All players report on time. #TeamWork',
        'Great win against {opponent}! The team showed incredible spirit. #MSUSports',
        'ZUSA tournament preparations in full swing. Let\'s bring it home! #ZUSA',
        'Tryouts for new players this Saturday. Show us what you\'ve got!',
    ],
}

COMMENT_TEMPLATES = [
    'Well done team! 🔥', 'Count me in!', 'This is amazing, keep it up!',
    'Proud to be part of this 💪', 'When is the next meeting?',
    'Great initiative!', 'See you there!', 'MSU to the world! 🌍',
    'Love this! ❤️', 'How do I join?', 'Best club on campus!',
    'Makorokoto! (Congratulations!)', 'Zvakanaka! (Awesome!)',
    'Can\'t wait for this event!', 'This is what MSU is all about!',
]
