# Generated by Django 5.2.8 on 2026-05-06 00:11

import django.contrib.postgres.search
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('workshop', 'Workshop'), ('conference', 'Conference'), ('competition', 'Competition'), ('seminar', 'Seminar'), ('social', 'Social Event'), ('other', 'Other')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('max_participants', models.IntegerField(default=50)),
                ('registration_deadline', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('attended', 'Attended'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registration_data', models.JSONField(blank=True, default=dict)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'activity_registrations',
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('denomination', models.CharField(choices=[('protestant', 'Protestant'), ('catholic', 'Catholic'), ('orthodox', 'Orthodox'), ('pentecostal', 'Pentecostal'), ('islamic', 'Islamic'), ('other', 'Other')], max_length=50)),
                ('service_times', models.JSONField(blank=True, default=dict)),
                ('pastor_name', models.CharField(blank=True, max_length=255)),
                ('pastor_contact', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'churches',
            },
        ),
        migrations.CreateModel(
            name='ChurchMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('ministry', models.CharField(blank=True, help_text='Choir, Youth, etc.', max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'church_memberships',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('arts', 'Arts & Culture'), ('science', 'Science'), ('business', 'Business & Entrepreneurship'), ('sports', 'Sports & Recreation'), ('service', 'Community Service'), ('academic', 'Academic'), ('other', 'Other')], max_length=50)),
                ('meeting_location', models.CharField(blank=True, max_length=255)),
                ('meeting_schedule', models.TextField(blank=True)),
                ('max_members', models.IntegerField(default=100)),
            ],
            options={
                'db_table': 'clubs',
            },
        ),
        migrations.CreateModel(
            name='ClubMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('position', models.CharField(blank=True, help_text='Officer, Member, etc.', max_length=100)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'club_memberships',
            },
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance_score', models.FloatField(default=1.0, help_text='Overall relevance score (0-100)')),
                ('engagement_score', models.FloatField(default=0.0, help_text='Score based on likes, comments, shares')),
                ('recency_score', models.FloatField(default=0.0, help_text='Score based on post age')),
                ('relationship_score', models.FloatField(default=0.0, help_text='Score based on user-org relationship')),
                ('priority_boost', models.FloatField(default=0.0, help_text='Manual priority adjustment')),
                ('source_type', models.CharField(choices=[('following', 'Following'), ('member', 'Member'), ('interest', 'Interest'), ('recommended', 'Recommended'), ('trending', 'Trending')], default='following', help_text='How this post entered the feed', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_scored_at', models.DateTimeField(auto_now=True, help_text='Last time score was updated')),
            ],
            options={
                'db_table': 'feeds',
                'ordering': ['-relevance_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField()),
                ('date', models.DateField()),
                ('member_count', models.IntegerField(default=0)),
                ('event_count', models.IntegerField(default=0)),
                ('engagement_score', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'organization_history',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PopularSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=200, unique=True)),
                ('search_count', models.IntegerField(default=1)),
                ('last_searched', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'popular_searches',
                'ordering': ['-search_count', '-last_searched'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(help_text='ID of the organization')),
                ('post_type', models.CharField(choices=[('announcement', 'Announcement'), ('event', 'Event'), ('achievement', 'Achievement'), ('general', 'General Update'), ('media', 'Media Post'), ('recruitment', 'Recruitment')], default='general', max_length=20)),
                ('title', models.CharField(blank=True, help_text='Optional title for post', max_length=200)),
                ('content', models.TextField(help_text='Post content/description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='posts/videos/')),
                ('video_thumbnail', models.ImageField(blank=True, help_text='Auto-generated video thumbnail', null=True, upload_to='posts/thumbnails/')),
                ('event_date', models.DateTimeField(blank=True, help_text='Event date and time', null=True)),
                ('event_location', models.CharField(blank=True, help_text='Event location', max_length=200)),
                ('event_link', models.URLField(blank=True, help_text='Event registration or info link')),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('members_only', 'Members Only'), ('followers_only', 'Followers Only'), ('admin_only', 'Admin Only')], default='public', max_length=20)),
                ('is_pinned', models.BooleanField(default=False, help_text='Pin post to top of feed')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('shares_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('likes_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'post_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_likes',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=20)),
                ('file', models.FileField(upload_to='posts/media/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('file_size', models.BigIntegerField(default=0, help_text='File size in bytes')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Video transcoding status', max_length=20)),
                ('transcoded_versions', models.JSONField(blank=True, default=dict, help_text='URLs of transcoded video versions (360p, 720p, 1080p)')),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_media',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'post_shares',
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_type', models.CharField(choices=[('club', 'Club'), ('church', 'Church'), ('sports_team', 'Sports Team'), ('activity', 'Activity')], max_length=50)),
                ('organization_id', models.UUIDField()),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('tags', models.TextField(blank=True, help_text='Space-separated tags')),
                ('search_vector', models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('name', weight='A'), '||', django.contrib.postgres.search.SearchVector('description', weight='B'), None), '||', django.contrib.postgres.search.SearchVector('category', weight='C'), None), '||', django.contrib.postgres.search.SearchVector('tags', weight='D'), None), output_field=models.TextField())),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('member_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'search_index',
            },
        ),
        migrations.CreateModel(
            name='SportsTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport_type', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('volleyball', 'Volleyball'), ('rugby', 'Rugby'), ('tennis', 'Tennis'), ('athletics', 'Athletics'), ('other', 'Other')], max_length=50)),
                ('division', models.CharField(choices=[('mens', "Men's"), ('womens', "Women's"), ('mixed', 'Mixed')], max_length=20)),
                ('coach', models.CharField(blank=True, max_length=255)),
                ('practice_schedule', models.TextField(blank=True)),
                ('max_roster_size', models.IntegerField(default=25)),
            ],
            options={
                'db_table': 'sports_teams',
            },
        ),
        migrations.CreateModel(
            name='SportsTeamMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=100)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('injured', 'Injured'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sports_team_memberships',
            },
        ),
        migrations.CreateModel(
            name='UserFollowOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(help_text='ID of the organization')),
                ('notify_on_posts', models.BooleanField(default=True, help_text='Notify on new posts')),
                ('notify_on_events', models.BooleanField(default=True, help_text='Notify on new events')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_follow_organization',
            },
        ),
        migrations.CreateModel(
            name='UserInterestOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.UUIDField(help_text='ID of the organization')),
                ('interest_level', models.CharField(choices=[('low', 'Low Interest'), ('medium', 'Medium Interest'), ('high', 'High Interest')], default='medium', help_text='Level of interest', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='User notes about interest')),
                ('contacted', models.BooleanField(default=False, help_text='Has organization contacted user?')),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_interest_organization',
            },
        ),
    ]
