# Generated by Django 5.2.8 on 2026-05-06 00:11

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='organizations.activity'),
        ),
        migrations.AddField(
            model_name='activityregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='church',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='church',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='churchmembership',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.church'),
        ),
        migrations.AddField(
            model_name='churchmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='church_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='faculty_advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advised_clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_club_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.club'),
        ),
        migrations.AddField(
            model_name='clubmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationhistory',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddIndex(
            model_name='popularsearch',
            index=models.Index(fields=['-search_count'], name='popular_search_count_idx'),
        ),
        migrations.AddIndex(
            model_name='popularsearch',
            index=models.Index(fields=['-last_searched'], name='popular_search_date_idx'),
        ),
        migrations.AddIndex(
            model_name='popularsearch',
            index=models.Index(fields=['query'], name='popular_search_query_idx'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(help_text='User who created the post', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.ForeignKey(help_text='Type of organization (Club, Church, Sports Team, Activity)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='feed',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.post'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent comment for nested replies', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='organizations.postcomment'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='organizations.post'),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postlike',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='organizations.post'),
        ),
        migrations.AddField(
            model_name='postlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='organizations.post'),
        ),
        migrations.AddField(
            model_name='postshare',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='organizations.post'),
        ),
        migrations.AddField(
            model_name='postshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='search_vector_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['organization_type', 'is_active'], name='search_type_active_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['is_active', 'is_approved', '-member_count'], name='search_status_count_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['category', '-member_count'], name='search_category_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['organization_id'], name='search_org_id_idx'),
        ),
        migrations.AddIndex(
            model_name='searchindex',
            index=models.Index(fields=['organization_type', 'organization_id'], name='search_org_type_id_idx'),
        ),
        migrations.AddField(
            model_name='sportsteam',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sportsteam',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sportsteammembership',
            name='sports_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.sportsteam'),
        ),
        migrations.AddField(
            model_name='sportsteammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userfolloworganization',
            name='content_type',
            field=models.ForeignKey(help_text='Type of organization (Club, Church, Sports Team, Activity)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userfolloworganization',
            name='user',
            field=models.ForeignKey(help_text='User following the organization', on_delete=django.db.models.deletion.CASCADE, related_name='following_organizations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userinterestorganization',
            name='content_type',
            field=models.ForeignKey(help_text='Type of organization', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='userinterestorganization',
            name='user',
            field=models.ForeignKey(help_text='User interested in the organization', on_delete=django.db.models.deletion.CASCADE, related_name='organization_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_active', 'is_approved'], name='activities_status_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['activity_type', 'is_active'], name='activities_type_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['start_date'], name='activities_start_date_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['end_date'], name='activities_end_date_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['registration_deadline'], name='activities_reg_deadline_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_recurring', 'start_date'], name='activities_recurring_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['created_by'], name='activities_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='activityregistration',
            index=models.Index(fields=['activity', 'status'], name='act_reg_act_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='activityregistration',
            index=models.Index(fields=['user', 'status'], name='activity_reg_user_status_idx'),
        ),
        migrations.AddIndex(
            model_name='activityregistration',
            index=models.Index(fields=['-registered_at'], name='activity_reg_registered_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='activityregistration',
            unique_together={('user', 'activity')},
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['is_active', 'is_approved'], name='churches_status_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['denomination', 'is_active'], name='churches_denomination_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['created_by'], name='churches_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['-created_at'], name='churches_created_idx'),
        ),
        migrations.AddIndex(
            model_name='churchmembership',
            index=models.Index(fields=['church', 'status'], name='church_mem_ch_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='churchmembership',
            index=models.Index(fields=['user', 'status'], name='church_mem_usr_stat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='churchmembership',
            unique_together={('user', 'church')},
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['is_active', 'is_approved'], name='clubs_status_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['category', 'is_active'], name='clubs_category_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['created_by'], name='clubs_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['-created_at'], name='clubs_created_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['is_approved', '-created_at'], name='clubs_approved_created_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmembership',
            index=models.Index(fields=['club', 'status'], name='club_mem_cl_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmembership',
            index=models.Index(fields=['user', 'status'], name='club_mem_usr_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='clubmembership',
            index=models.Index(fields=['status', '-joined_at'], name='club_mem_stat_join_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clubmembership',
            unique_together={('user', 'club')},
        ),
        migrations.AlterUniqueTogether(
            name='organizationhistory',
            unique_together={('content_type', 'object_id', 'date')},
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content_type', 'object_id'], name='posts_org_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', '-created_at'], name='posts_author_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', '-created_at'], name='posts_type_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_pinned', '-created_at'], name='posts_pinned_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['visibility', '-created_at'], name='posts_visibility_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_active', '-created_at'], name='posts_active_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='posts_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['event_date'], name='posts_event_date_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['user', '-created_at'], name='feeds_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['user', '-relevance_score'], name='feeds_user_score_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['user', 'is_read', '-relevance_score'], name='feeds_user_read_score_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['is_read', '-created_at'], name='feeds_read_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['source_type', '-created_at'], name='feeds_source_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['post', 'user'], name='feeds_post_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('user', 'post')},
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['post', '-created_at'], name='post_comments_post_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['user', '-created_at'], name='post_comments_user_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['parent', '-created_at'], name='post_comments_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='postcomment',
            index=models.Index(fields=['is_active', '-created_at'], name='post_comments_active_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', 'user'], name='post_likes_post_user_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['post', '-created_at'], name='post_likes_post_idx'),
        ),
        migrations.AddIndex(
            model_name='postlike',
            index=models.Index(fields=['user', '-created_at'], name='post_likes_user_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together={('post', 'user')},
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post', 'order'], name='post_media_post_order_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['media_type'], name='post_media_type_idx'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['processing_status'], name='post_media_status_idx'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['post', '-created_at'], name='post_shares_post_idx'),
        ),
        migrations.AddIndex(
            model_name='postshare',
            index=models.Index(fields=['user', '-created_at'], name='post_shares_user_idx'),
        ),
        migrations.AddIndex(
            model_name='sportsteam',
            index=models.Index(fields=['is_active', 'is_approved'], name='sports_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sportsteam',
            index=models.Index(fields=['sport_type', 'is_active'], name='sports_type_idx'),
        ),
        migrations.AddIndex(
            model_name='sportsteam',
            index=models.Index(fields=['division', 'sport_type'], name='sports_division_type_idx'),
        ),
        migrations.AddIndex(
            model_name='sportsteam',
            index=models.Index(fields=['created_by'], name='sports_creator_idx'),
        ),
        migrations.AddIndex(
            model_name='sportsteam',
            index=models.Index(fields=['-created_at'], name='sports_created_idx'),
        ),
        migrations.AddIndex(
            model_name='sportsteammembership',
            index=models.Index(fields=['sports_team', 'status'], name='sports_mem_tm_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='sportsteammembership',
            index=models.Index(fields=['user', 'status'], name='sports_mem_usr_stat_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='sportsteammembership',
            unique_together={('user', 'sports_team')},
        ),
        migrations.AddIndex(
            model_name='userfolloworganization',
            index=models.Index(fields=['user', '-created_at'], name='follow_org_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userfolloworganization',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='follow_org_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='userfolloworganization',
            index=models.Index(fields=['user', 'content_type'], name='follow_org_user_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='userfolloworganization',
            index=models.Index(fields=['user', 'notify_on_posts'], name='follow_org_notify_posts_idx'),
        ),
        migrations.AddIndex(
            model_name='userfolloworganization',
            index=models.Index(fields=['user', 'notify_on_events'], name='follow_org_notify_events_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userfolloworganization',
            unique_together={('user', 'content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='userinterestorganization',
            index=models.Index(fields=['user', '-created_at'], name='interest_org_user_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterestorganization',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='interest_org_ct_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterestorganization',
            index=models.Index(fields=['interest_level', '-created_at'], name='interest_org_level_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterestorganization',
            index=models.Index(fields=['contacted', '-created_at'], name='interest_org_contacted_idx'),
        ),
        migrations.AddIndex(
            model_name='userinterestorganization',
            index=models.Index(fields=['content_type', 'object_id', 'contacted'], name='interest_org_ct_contacted_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userinterestorganization',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
