# Generated by Django 5.2.8 on 2026-05-06 03:15

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_enable_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma-separated tags for interest matching (e.g., technology, sports, prayer)', max_length=500),
        ),
        migrations.AddField(
            model_name='activity',
            name='events_count',
            field=models.IntegerField(default=0, help_text='Total upcoming events'),
        ),
        migrations.AddField(
            model_name='activity',
            name='followers_count',
            field=models.IntegerField(default=0, help_text='Total followers'),
        ),
        migrations.AddField(
            model_name='activity',
            name='members_count',
            field=models.IntegerField(default=0, help_text='Total active members'),
        ),
        migrations.AddField(
            model_name='activity',
            name='posts_count',
            field=models.IntegerField(default=0, help_text='Total posts'),
        ),
        migrations.AddField(
            model_name='church',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma-separated tags for interest matching (e.g., technology, sports, prayer)', max_length=500),
        ),
        migrations.AddField(
            model_name='church',
            name='events_count',
            field=models.IntegerField(default=0, help_text='Total upcoming events'),
        ),
        migrations.AddField(
            model_name='church',
            name='followers_count',
            field=models.IntegerField(default=0, help_text='Total followers'),
        ),
        migrations.AddField(
            model_name='church',
            name='members_count',
            field=models.IntegerField(default=0, help_text='Total active members'),
        ),
        migrations.AddField(
            model_name='church',
            name='posts_count',
            field=models.IntegerField(default=0, help_text='Total posts'),
        ),
        migrations.AddField(
            model_name='club',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma-separated tags for interest matching (e.g., technology, sports, prayer)', max_length=500),
        ),
        migrations.AddField(
            model_name='club',
            name='events_count',
            field=models.IntegerField(default=0, help_text='Total upcoming events'),
        ),
        migrations.AddField(
            model_name='club',
            name='followers_count',
            field=models.IntegerField(default=0, help_text='Total followers'),
        ),
        migrations.AddField(
            model_name='club',
            name='members_count',
            field=models.IntegerField(default=0, help_text='Total active members'),
        ),
        migrations.AddField(
            model_name='club',
            name='posts_count',
            field=models.IntegerField(default=0, help_text='Total posts'),
        ),
        migrations.AddField(
            model_name='post',
            name='reposts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sportsteam',
            name='categories',
            field=models.CharField(blank=True, help_text='Comma-separated tags for interest matching (e.g., technology, sports, prayer)', max_length=500),
        ),
        migrations.AddField(
            model_name='sportsteam',
            name='events_count',
            field=models.IntegerField(default=0, help_text='Total upcoming events'),
        ),
        migrations.AddField(
            model_name='sportsteam',
            name='followers_count',
            field=models.IntegerField(default=0, help_text='Total followers'),
        ),
        migrations.AddField(
            model_name='sportsteam',
            name='members_count',
            field=models.IntegerField(default=0, help_text='Total active members'),
        ),
        migrations.AddField(
            model_name='sportsteam',
            name='posts_count',
            field=models.IntegerField(default=0, help_text='Total posts'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='church',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/images/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='posts/videos/', validators=[apps.core.validators.FileSizeValidator(max_size=104857600), apps.core.validators.MimeTypeValidator(allowed_types=['video/mp4', 'video/mpeg', 'video/quicktime', 'video/x-msvideo'])]),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_thumbnail',
            field=models.ImageField(blank=True, help_text='Auto-generated video thumbnail', null=True, upload_to='posts/thumbnails/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='file',
            field=models.FileField(upload_to='posts/media/', validators=[apps.core.validators.FileSizeValidator(max_size=104857600)]),
        ),
        migrations.AlterField(
            model_name='sportsteam',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
