# Generated by Django 5.2.8 on 2026-05-06 05:47

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_activity_categories_activity_events_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_covers/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='church',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='church',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_covers/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='club',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_covers/', validators=[apps.core.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name='sportsteam',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='sportsteam',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_covers/', validators=[apps.core.validators.validate_image_file]),
        ),
    ]
