# Generated by Django 5.2.8 on 2026-05-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='followers_count_val',
            field=models.IntegerField(db_column='followers_count', default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='following_count_val',
            field=models.IntegerField(db_column='following_count', default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, help_text='Comma-separated interests (e.g., coding, music, sports)', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='posts_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
